development:
  host: localhost
  database: groups_sharevision_development

test:
  host: localhost
  database: groups_sharevision_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
