development:
  host: localhost
  database: krum_development

test:
  host: localhost
  database: krum_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
