USERNAME: 'admin'
PASSWORD: 'password'
SENDER_EMAIL: 'noreply@sharevisionteam.org'
RECIPIENT_EMAIL: 'samnang.chhun@gmail.com'
S3_BUCKET_NAME: 'dev.krum'
CALENDAR: '<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23cccccc&amp;src=jh7s6tdpem67eojoeufbbvbva4%40group.calendar.google.com&amp;color=%235229A3&amp;ctz=Asia%2FPhnom_Penh" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>'
